global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: "app-health"
    metrics_path: /
    static_configs:
      - targets:
          - "<APP_SERVER_IP>:80"
